### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by DanRotaru** [coltongriffith/fluenticons#13]
In Material Design Icons are missing some icons, for example I search 'open-in-new' and it doesn't exist.
But on official https://pictogrammers.com/library/mdi/ it exists.

**Comment by ajaxStardust** [comment]
I got this Warn when attempting the dev build: (e.g. yarn dev )
~~~~~~~

 WARN  No provided fonts.                                                                   nuxt:google-fonts 20:50:50

i Discovered Components: .nuxt/components/readme.md                                                           20:50:56
√ Builder initialized                                                                                         20:50:56
√ Nuxt files generated

**Comment by ajaxStardust** [comment]
Does this mean the correct fonts aren't installed on my system? Or not included in the repo? I'm not super familiar w/ "FLuent" if that's a font family... 

(sorry GitHub running too slow to edit above)

**Comment by ajaxStardust** [comment]
FYI: after some wait time, it appears to be working. I didn't do anything differently, but came back to the (forgotten) open terminal later, and the "Listening on: http..." was there (unlike before)

[https://imgur.com/9o98Mc8](https://imgur.com/9o98Mc8)
